apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logs-*
    isDefault: true
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.13.4
      maxConcurrentShardRequests: 5
